### ISSUE TITLE
database file

### ISSUE THREAD

**Issue by chuapeikun** [CyberRad/Ticket#1]
can you upload a complete sql file that included users

**Comment by CyberRad** [comment]
This was dropped when our hackerspace closed. So I can't get you a SQL dump. But you can check out processlogin.php to determine what you need. You will need to create a table called users with id, username, password, admin fields. The id field is auto incremented with each new user (row). The admin field is essentially a bit that determines if the user can edit/add events.

**Comment by chuapeikun** [comment]
what should i fill in the admin field?

**Comment by CyberRad** [comment]
Its a bit as noted above. That means either a 1 or a 0. 1 = admin 0 = non-admin.

**Comment by chuapeikun** [comment]
awwwww thanks a lot !!!!! you are so nice!!!!!!!! god bless!!!

**Comment by chuapeikun** [comment]
## -- Table structure for table `users`

CREATE TABLE IF NOT EXISTS `users` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `username` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `admin` int(30) NOT NULL,

  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=5 ;

## 

## -- Dumping data for table `users`

when i login in , still cant go to action=admin :(

**Comment by CyberRad** [comment]
What was the error? Was your password encrypted using the Portable PHP password hashing framework (passwordhash.php)? Please take a look at the code you are trying to run to better understand this project. Your questions should be answered if you step through the code.
